src/tymenu/main/forms.py
from __future__ import annotations

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class ChangeUsernameForm(FlaskForm):
    username = StringField("New Username", validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField("Update Username")
    cancel = SubmitField(label="Cancel", render_kw={"formnovalidate": True})

src/tymenu/main/__init__.py
from .blueprint import main_blueprint
from . import views
from . import errors

__all__ = ["main_blueprint", "views", "errors"]

src/tymenu/main/blueprint.py
from __future__ import annotations

from flask import Blueprint

main_blueprint = Blueprint("main", __name__)

src/tymenu/main/views.py
from __future__ import annotations

import logging

from flask import abort, current_app, flash, redirect, render_template, request, url_for
from sqlalchemy import exc

from tymenu.decorators import login_required
from tymenu.models import Recipe, User
from tymenu.resources import get_db

from . import main_blueprint as main
from .forms import ChangeUsernameForm

logger = logging.getLogger(__name__)


@main.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    pagination = Recipe.query.order_by(Recipe.timestamp.desc()).paginate(
        page=page,
        per_page=current_app.config["TYMENU_RECIPES_PER_PAGE"],
        error_out=False,
    )
    recipes = pagination.items
    return render_template("index.html", recipes=recipes, recipes_list_max=5, pagination=pagination)


@main.route("/users")
def users():
    page = request.args.get("page", 1, type=int)
    pagination = User.query.order_by(User.id.asc()).paginate(
        page=page,
        per_page=current_app.config["TYMENU_USERS_PER_PAGE"],
        error_out=False,
    )
    users = pagination.items
    return render_template("main/users.html", users=users, pagination=pagination)


@main.route("/profile/<int:id>")
def profile(id):
    user: User = User.query.get_or_404(id)
    page = request.args.get("page", 1, type=int)
    pagination = user.recipes.order_by(Recipe.timestamp.desc()).paginate(
        page=page,
        per_page=5,
        error_out=False,
    )
    recipes = pagination.items
    return render_template(
        "main/profile.html",
        user=user,
        recipes=recipes,
        recipes_list_max=5,
        pagination=pagination,
    )


@main.route("/profile/change_username/<int:id>", methods=["GET", "POST"])
@login_required
def change_username(id):
    user: User = User.query.get_or_404(id)
    if not user.is_current_user:
        # Only the user itself is allowed to change this.
        abort(403)

    form = ChangeUsernameForm()
    if form.cancel.data:
        return redirect(url_for(".profile", id=id))

    if form.validate_on_submit():
        user.username = form.username.data
        db = get_db()
        try:
            db.session.add(user)
            db.session.commit()
        except exc.IntegrityError as e:
            db.session.rollback()
            flash("Username already exists.")
            logger.error("Failed to change username for user %d. Error: %s", user.id, e)
        except Exception as e:
            db.session.rollback()
            flash(f"Failed to change username: {e}")
            logger.error("Failed to change username for user %d. Error: %s", user.id, e)
        else:
            flash(f"Successfully changed username to {user.username}")
        return redirect(url_for(".profile", id=id))

    return render_template("main/change_username.html", form=form)


@main.route("/links")
def links():
    return render_template("links.html")

src/tymenu/templates/main/change_username.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TyMenu - Change Username{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Change Your Username</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

src/tymenu/templates/main/profile.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}TyMenu - Profile{% endblock %}

{% block page_content %}

<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=150) }}">
    <div class="profile-header">
        <h1>{{ user.username }}</h1>
        Role: {{ user.role }}<br>
        Member since: {{ moment(user.member_since).format('LLL') }}<br>
        Number of recipes: {{ user.recipes.count() }}
    </div>
    {% if current_user.is_administrator() %}
    <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
    {% endif %}
    {% if user.is_current_user %}
    <div>
        <a href="{{ url_for('main.change_username', id=user.id) }}">Change Username</a>
    </div>
    {% endif %}

</div>

<div class="pagination">
    {{ macros.pagination_widget(pagination, '.profile', id=user.id) }}
</div>
{% include '_recipes.html' %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.profile', id=user.id) }}
</div>



{% endblock %}

src/tymenu/templates/main/users.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}TyMenu - Users{% endblock %}

{% block page_content %}

<div class="pagination">
    {{ macros.pagination_widget(pagination, '.users') }}
</div>
{% include '_users.html' %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.users') }}
</div>



{% endblock %}